language: c
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq flex bison gcc-4.8-multilib
script:
  - scripts/download-d8.sh
  - scripts/travis-build.sh
  - scripts/travis-test.sh
compiler:
  - clang
  - gcc
