language: c
before_install:
  - scripts/travis-before-install.sh
addons:
  apt:
    packages:
      - re2c
      - bison
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - linux-libc-dev:i386
script:
  - scripts/travis-build.sh
  - scripts/travis-test.sh
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc-i686
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: clang
      env: SANITIZER=asan
# Disabled because MSAN seems to have stopped working on Travis.
#    - os: linux
#      dist: trusty
#      compiler: clang
#      env: SANITIZER=msan
    - os: linux
      dist: trusty
      compiler: clang
      env: SANITIZER=lsan
    - os: linux
      dist: trusty
      compiler: clang
      env: SANITIZER=ubsan
    - os: osx
      compiler: clang

  # Allow failures on the Mac bots. We'd rather not, but they are quite slow.
  allow_failures:
    - os: osx
      compiler: clang

  fast_finish: true
